### ISSUE TITLE
売りの注文が失敗する

### ISSUE THREAD

**Issue by uedatakeshi** [uedatakeshi/kabusphp#25]
原因調査中

**Comment by uedatakeshi** [comment]
"{\"Code\":4003001,\"Message\":\"ワンショット：金額エラー\"}"] []
"Symbol":"3903"
"Qty":100,"Price":1025,
"ExpireDay":"20200930"
値幅制限超えてたのでは？

**Comment by uedatakeshi** [comment]
この日の値幅は〜1122だったはず。

**Comment by uedatakeshi** [comment]
https://github.com/kabucom/kabusapi/issues/41

kabuステーション（アプリの方）にワンショット金額の設定があったような気がします。

**Comment by uedatakeshi** [comment]
10/5今日もだめ。
買い733円なので754円で売り入れてるはずだが。。
前日終値665円なので値幅制限は765円。

**Comment by uedatakeshi** [comment]
string(45) "{"Result":0,"OrderId":"20201005A01N58166125"}"
PHP Notice:  Undefined variable: kabus in C:\Users\ueda\app\kabusphp\read.php on
 line 98

Notice: Undefined variable: kabus in C:\Users\ueda\app\kabusphp\read.php on line 98
PHP Fatal error:  Uncaught Error: Call to a member function getsendorder() on null in C:\Users\ueda\app\kabusphp\read.php:98
Stack trace:
#0 C:\Users\ueda\app\kabusphp\read.php(70): uriChumon(Array, '20201005A01N581...', '5337')
#1 {main}
  thrown in C:\Users\ueda\app\kabusphp\read.php on line 98

Fatal error: Uncaught Error: Call to a member function getsendorder() on null in C:\Users\ueda\app\kabusphp\read.php:98
Stack trace:
#0 C:\Users\ueda\app\kabusphp\read.php(70): uriChumon(Array, '20201005A01N581...', '5337')
#1 {main}
  thrown in C:\Users\ueda\app\kabusphp\read.php on line 98
